use newer syntax [[ ... ]]

diff --git a/lkm b/lkm
--- a/lkm
+++ b/lkm
@@ -18,17 +18,17 @@ name=$(basename "${0}")
 runcmd()
 {
 local SEP="------------------------------"
-[ $# -eq 0 ] && return
+[[ $# -eq 0 ]] && return
 echo "${SEP}
 $*
 ${SEP}"
 eval "$@"
-[ $? -ne 0 ] && echo " ^--[FAILED]"
+[[ $? -ne 0 ]] && echo " ^--[FAILED]"
 }
 
 ### "main" here
 
-[ $# -ne 1 ] && {
+[[ $# -ne 1 ]] && {
 	echo "Usage: ${name} name-of-kernel-module-file (without the .c)"
 	exit 1
 }
@@ -49,7 +49,7 @@ runcmd "sudo rmmod $1 2> /dev/null" || true
 runcmd "sudo dmesg -C" || true
 runcmd "make || exit 1" || true
 
-[ ! -f "$1".ko ] && {
+[[ ! -f "$1".ko ]] && {
   echo "[!] ${name}: $1.ko has not been built, aborting..."
   exit 1
 }
